# Written by Lance Zeligman 
# This workflow is loosely inspired by the Hashicorp Workflow 
# with a focus on using terraform and S3 hosted state files 
# rather than terraform cloud
---

name: Terraform Speculative Run

on:
    pull_request:
      branches:
        - 'main'
        - 'feature/**'
      types: [opened, reopened, synchronize]
      paths-ignore:
        - ".github/**"
        - "**.md"
    push:
      branches:
        - 'main'
        - 'feature/**'
      paths-ignore:
        - ".github/**"
        - "**.md"

jobs:
    terraform-speculative-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v5
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: eu-west-1

            - name: Setup Terraform CLI
              uses: hashicorp/setup-terraform@v3

            - name: Terraform Init
              run: |
                echo $(pwd)
                echo "tfpath ${{ github.event.inputs }}"
                echo "Running Tf Init"
                terraform init
            
            - name: Terraform Validate
              run: |
                terraform validate
            
            - name: Terraform Plan
              run: |
                terraform plan